### ISSUE TITLE
Dirichlet L-functions (meta issue and feature wishlist)

### ISSUE THREAD

**Issue by fredrik-johansson** [fredrik-johansson/arb#164]
- [ ] Review all code in the dirichlet branch thoroughly and merge into master (PR #163).

- [ ] Add more example programs.

- [ ] Series expansions.
- [ ] Evaluation using reflection formula.
- [ ] Generalized Bernoulli numbers / evaluation at -n? Functions to compute the exact rational coefficients?
- [ ] Euler product evaluation for re(s) >> 0.

- [ ] Move Hurwitz zeta code to the Dirichlet module and tidy the code a bit.
- [ ] Look for ways to optimize Hurwitz zeta for rational parameter.

- [ ] Possible use of double and double-double arithmetic to speed up truncated L-series.
- [ ] Improve parameter selection in Euler-Maclaurin summation and avoid
      unnecessary slowdown for large height.
- [ ] Allow the user to limit the memory allowed for sieving etc.

- [ ] Completed L-functions / Riemann xi-function, Z-function, Siegel theta function, Gram points.
- [ ] Computing zeros.
- [ ] Polynomial approximation with error bounds.
- [ ] Riemann-Siegel formula.
- [ ] Grid evaluation.
